repos:

  # pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      # - id: no-commit-to-branch
      #   args: ['--branch', 'main']
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml
      - id: check-xml
      - id: check-json
      - id: pretty-format-json
        args: ['--no-sort-keys', '--autofix', '--indent=4']
      - id: end-of-file-fixer
        exclude: \.json$
        files: \.java$|\.xml$
      - id: trailing-whitespace
      - id: mixed-line-ending

  # for commit message formatting
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.4
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: format-java
        name: Format Java (Spotless)
        entry: mvn spotless:apply
        language: system
        files: \.java$
        pass_filenames: false

      - id: format-js
        name: Format JS/JSX/CSS/HTML (Prettier - webapp)
        entry: sh -c 'cd src/main/webapp && npm run format'
        language: system
        files: ^src/main/webapp/src/.*\.(js|jsx|css|html)$
        pass_filenames: false

      - id: format-docs
        name: Format JS/JSX/CSS/HTML (Prettier - docs)
        entry: sh -c 'cd docs && npm run format'
        language: system
        files: ^docs/src/.*\.(js|jsx|css|html)$
        pass_filenames: false