name: Validate Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/maven-build.yml
    with:
      version: ${{ github.sha }}
      skip-tests: false
      retention-days: 30